"""constants."""

MAX_LENGTH_FOR_STR = 30

# USER
USER = 'user'
MODERATOR = 'moderator'
ADMIN = 'admin'
LOCALIZED_USER = 'Пользователь'
LOCALIZED_MODERATOR = 'Модератор'
LOCALIZED_ADMIN = 'Администратор'
ROLE_CHOICES = [
    (USER, LOCALIZED_USER),
    (MODERATOR, LOCALIZED_MODERATOR),
    (ADMIN, LOCALIZED_ADMIN),
]
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_EMAIL_ADDRESS = 254


# TITLE
MIN_VALUE_SCORE = 1
MAX_VALUE_SCORE = 10

# CATEGORY/GENRE
MAX_LENGTH_NAME = 256
MAX_LENGTH_SLUG = 50
